# Generated by Django 4.0.1 on 2022-02-15 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def handel_null_value_of_core_value(apps, schema_editor):
    core_value_model = apps.get_model('personal_to_dos', 'CoreValue')
    db_alias = schema_editor.connection.alias
    core_value_model.objects.using(db_alias).filter(user__isnull=True).delete()


def reverse_handel_null_value_of_core_value(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personal_to_dos', '0002_alter_corevalue_user'),
    ]

    operations = [
        migrations.RunPython(code=handel_null_value_of_core_value,
                             reverse_code=reverse_handel_null_value_of_core_value
                             ),
        migrations.AlterField(
            model_name='corevalue',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                    verbose_name='User'),
        ),

    ]
