# Generated by Django 4.0.1 on 2022-02-17 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_to_dos', '0003_alter_corevalue_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corevalue',
            old_name='user',
            new_name='owner',
        ),
    ]
