# Generated by Django 4.0.1 on 2022-02-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_to_dos', '0005_alter_corevalue_owner'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='corevalue',
            index=models.Index(fields=['owner'], name='personal_to_owner_i_cd47f1_idx'),
        ),
    ]
