# Generated by Django 4.0.1 on 2022-02-18 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personal_to_dos', '0006_corevalue_personal_to_owner_i_cd47f1_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corevalue',
            name='create_date',
            field=models.DateField(auto_now=True, verbose_name='Create date'),
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('create_date', models.DateField(auto_now=True, verbose_name='Create date')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due date')),
                ('group', models.CharField(blank=True, choices=[('immediately', 'Immediately'), ('short term', 'Short term'), ('middle term', 'Middle term'), ('long term', 'Long term'), ('Very Long term', 'Very Long term')], max_length=30, null=True, verbose_name='Group')),
                ('core_values', models.ManyToManyField(to='personal_to_dos.CoreValue', verbose_name='Core values')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_owner', related_query_name='%(app_label)s_%(class)s_owners', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
