# Generated by Django 4.0.1 on 2022-02-21 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personal_to_dos', '0007_alter_corevalue_create_date_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('create_date', models.DateField(auto_now=True, verbose_name='Create date')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('start_date_time', models.DateTimeField(verbose_name='Start date time')),
                ('repeat_type', models.PositiveSmallIntegerField(choices=[(0, 'No Repeat'), (1, 'Day'), (2, 'Week'), (3, 'Month'), (4, 'Year')], verbose_name='Repeat Type')),
                ('repeat_period', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Repeat period')),
                ('selected_week_days', models.JSONField(default=[], verbose_name='Selected week days')),
                ('end_type', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Never'), (1, 'On Specific date'), (2, 'After specific occurrence')], null=True, verbose_name='End repeat type')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('end_after_occurrence', models.PositiveIntegerField(blank=True, null=True, verbose_name='End after occurrence')),
                ('completely_done', models.BooleanField(default=False, verbose_name='Task is completely done')),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personal_to_dos.goal', verbose_name='Related Goal')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_owner', related_query_name='%(app_label)s_%(class)s_owners', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
