# Generated by Django 4.0.1 on 2022-02-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_to_dos', '0008_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='selected_week_days',
            field=models.JSONField(blank=True, default=[], null=True, verbose_name='Selected week days'),
        ),
    ]
