# Generated by Django 4.0.1 on 2022-02-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_to_dos', '0009_alter_task_selected_week_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='repeat_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No repeat'), (1, 'Day'), (2, 'Week'), (3, 'Month'), (4, 'Year')], verbose_name='Repeat Type'),
        ),
    ]
