# Generated by Django 4.0.1 on 2022-03-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_to_dos', '0010_alter_task_repeat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='repeat_period',
            field=models.IntegerField(blank=True, null=True, verbose_name='Repeat period'),
        ),
    ]
