# Generated by Django 4.0.1 on 2022-03-02 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personal_to_dos', '0011_alter_task_repeat_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartiallyCompletedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('create_date', models.DateField(auto_now=True, verbose_name='Create date')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_owner', related_query_name='%(app_label)s_%(class)s_owners', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_to_dos.task')),
            ],
            options={
                'verbose_name': 'Partially completed task',
                'verbose_name_plural': 'Partially completed tasks',
            },
        ),
    ]
