# Generated by Django 4.0.1 on 2022-03-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_to_dos', '0012_partiallycompletedtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Never'), (1, 'On specific date'), (2, 'After specific occurrence')], null=True, verbose_name='End repeat type'),
        ),
    ]
