# Generated by Django 4.0.1 on 2022-03-03 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_to_dos', '0013_alter_task_end_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partiallycompletedtask',
            options={'default_related_name': 'partially_completed_task', 'verbose_name': 'Partially completed task', 'verbose_name_plural': 'Partially completed tasks'},
        ),
    ]
