# Generated by Django 4.0.1 on 2022-03-03 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_to_dos', '0014_alter_partiallycompletedtask_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='partiallycompletedtask',
            unique_together={('task', 'create_date')},
        ),
    ]
