# Generated by Django 4.0.1 on 2022-03-17 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_to_dos', '0015_alter_partiallycompletedtask_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='selected_week_days',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Selected week days'),
        ),
    ]
