# Generated by Django 4.0.1 on 2022-03-17 17:14

from django.core.management import call_command
from django.db import migrations


def load_core_value_suggestions(apps, schema_editor):
    print('load core values suggestions')
    call_command('loaddata', 'core_values_suggestions.json', verbosity=2)


def reverse_load_core_value_suggestions(apps, schema_editor):
    field_values_suggestion = apps.get_model('core', 'fieldvaluessuggestion')
    field_values_suggestion.objects.filter(pk__lte=102).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('personal_to_dos', '0016_alter_task_selected_week_days'),
    ]

    operations = [
        migrations.RunPython(
            load_core_value_suggestions,
            reverse_load_core_value_suggestions)
    ]
